from rest_framework import serializers
from .models import CloudAccount, IAMPolicy
from django.contrib.auth import get_user_model


User = get_user_model()

class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ('id', 'email', 'username', 'is_2fa_enabled', 'date_joined')
        # We don't include the password in the fields because 
        # it should only be handled during creation (Signup)

    def create(self, validated_data):
        # This ensures the password is saved as a secure hash
        user = User.objects.create_user(
            email=validated_data['email'],
            password=self.context['request'].data.get('password'),
            username=validated_data.get('username')
        )
        return user

class CloudAccountSerializer(serializers.ModelSerializer):
    class Meta:
        model = CloudAccount
        fields = ['id', 'name', 'platform', 'is_active', 'access_key', 'secret_key', 'extra_config', 'last_sync_status']
        extra_kwargs = {
            'secret_key': {'write_only': True}
        }


class IAMPolicySerializer(serializers.ModelSerializer):
    # This pulls the name of the User or Role the policy belongs to
    entity_name = serializers.ReadOnlyField(source='entity.name')
    platform = serializers.ReadOnlyField(source='entity.cloud_account.platform')

    class Meta:
        model = IAMPolicy
        fields = [
            'id', 
            'entity_name', 
            'platform',
            'name', 
            'document', 
            'risk_score', 
            'is_vulnerable', 
            'finding_details', 
            'updated_at'
        ]
        # We mark these as read_only because they are generated by our 
        # SecurityScanner, not by the user's manual input.
        read_only_fields = ['risk_score', 'is_vulnerable', 'finding_details', 'updated_at']

    def validate_document(self, value):
        """Ensure the policy document is a valid dictionary (JSON)."""
        if not isinstance(value, dict):
            raise serializers.ValidationError("Policy document must be a valid JSON object.")
        return value