# Generated by Django 6.0.1 on 2026-01-11 12:52

import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Production AWS', max_length=100)),
                ('platform', models.CharField(choices=[('aws', 'Amazon Web Services'), ('azure', 'Microsoft Azure'), ('gcp', 'Google Cloud Platform')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_status', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('access_key', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True)),
                ('secret_key', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True)),
                ('extra_config', encrypted_fields.fields.EncryptedJSONField(blank=True, help_text='Store TenantID, ProjectID, etc.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
