# Generated by Django 6.0.1 on 2026-01-11 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cloudaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAMEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('arn_or_id', models.CharField(help_text='The unique cloud identifier (e.g. AWS ARN)', max_length=512, unique=True)),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('role', 'Role'), ('group', 'Group')], max_length=10)),
                ('created_at_in_cloud', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.cloudaccount')),
            ],
        ),
        migrations.CreateModel(
            name='IAMPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.JSONField(help_text='The raw JSON policy structure')),
                ('is_vulnerable', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=0)),
                ('finding_details', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='core.iamentity')),
            ],
        ),
    ]
